### ISSUE TITLE
ENOENT error on windows

### ISSUE THREAD

**Issue by aschekatihin** [paprikka/lana-cli#3]
Caused by this issue: https://github.com/nodejs/node/issues/3675  There is also fix provided in comments.

**Comment by paprikka** [comment]
Tested on a few VMs, the issue turned out to have two causes: the one you mentioned and reference to an IPC channel (not useful in this case).

Couldn't test it on Win10, as my internet's been a bit sluggish today, so if you find anything else - shout:)

**Comment by aschekatihin** [comment]
Works on Win 10, thanks!
